export default {
  PLAYER_GAMES_REQUEST: 'PLAYER_GAMES_REQUEST',
  PLAYER_GAMES_SUCCESS: 'PLAYER_GAMES_SUCCESS',
  PLAYER_GAMES_FAILURE: 'PLAYER_GAMES_FAILURE',
  UPDATE_PLAYER_GAMES_REQUEST: 'UPDATE_PLAYER_GAMES_REQUEST',
  UPDATE_PLAYER_GAMES_SUCCESS: 'UPDATE_PLAYER_GAMES_SUCCESS',
  UPDATE_PLAYER_GAMES_FAILURE: 'UPDATE_PLAYER_GAMES_FAILURE',
};
