export default {
  GAME_REQUEST: 'GAME_REQUEST',
  GAME_SUCCESS: 'GAME_SUCCESS',
  GAME_FAILURE: 'GAME_FAILURE',
  GAMES_REQUEST: 'GAMES_REQUEST',
  GAMES_SUCCESS: 'GAMES_SUCCESS',
  GAMES_FAILURE: 'GAMES_FAILURE',
};
